<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.5" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUi" Version="10.0.0-*" />
  </ItemGroup>

  <!-- ДОБАВЬТЕ ЭТОТ БЛОК, ЕСЛИ ЕГО НЕТ -->
  <ItemGroup>
    <ProjectReference Include="..\Study.LabWork3.Storage\Study.LabWork3.Storage.csproj" />
  </ItemGroup>
</Project>
